platform: linux
caches:
  - path: ../../../go/pkg
  - path: ../../../usr/local/share/.cache
  - path: ../../../root/.cache
  - path: ../../../root/.yarn
inputs:
  - name: goalert
outputs:
  - name: bin
image_resource:
  type: registry-image
  source: { repository: goalert/build-env, tag: go1.21.3-postgres13 }
run:
  path: sh
  dir: goalert
  args: [-e, ./devtools/ci/tasks/scripts/build-all.sh, ../bin/]
