platform: linux
params:
  BUILD_INTEGRATION: '1'
caches:
  - path: ../../../go/pkg
  - path: goalert/node_modules
  - path: goalert/web/src/node_modules
  - path: ../../../usr/local/share/.cache
  - path: ../../../root/.cache
inputs:
  - name: goalert
outputs:
  - name: bin
image_resource:
  type: registry-image
  source: { repository: goalert/build-env, tag: go1.23.3-postgres13 }
run:
  path: sh
  dir: goalert
  args: [-e, ./devtools/ci/tasks/scripts/build-binaries.sh, ../bin/]
