platform: linux
caches:
  - path: ../../../go/pkg
  - path: ../../../root/.cache
inputs:
  - name: goalert
outputs:
  - name: debug
image_resource:
  type: registry-image
  source: { repository: goalert/build-env, tag: go1.21.0-postgres13 }
run:
  path: sh
  dir: goalert
  args: [-e, ./devtools/ci/tasks/scripts/test-smoketest.sh]
